### ISSUE TITLE
Alpha 1.0.2 memory usage spike

### ISSUE THREAD

**Issue by ffallah** [TGMTProto/MTProtoProxy#10]
I noticed memory usage of the process goes very high suddenly and after a while returns back to normal.
I witnessed the memory usage going to 2GB and then returning back to 20MB after a while.
Blue line shows the memory usage :

![c10](https://user-images.githubusercontent.com/9332653/40133732-d3a09a44-5955-11e8-8e4e-9e08dd477550.PNG)

Edit: The increase in memory usage is not always spiky, sometimes it gradually grows up to 300-500MB and suddenly drops back to 10-20MB. I suspect it could be .Net garbage collector which reduces the memory usage.
I would suggest to manage the resources more explicitly and dispose of them when connections are closed or terminated.

**Comment by TGMTProrto** [comment]
This bug has been fixed in the new version(alpha 1.0.3) Use the new version and report it if there is a problem.
