### ISSUE TITLE
Alpha 1.0.3 index out of range

### ISSUE THREAD

**Issue by ffallah** [TGMTProto/MTProtoProxy#11]
![c15](https://user-images.githubusercontent.com/9332653/40272991-5c598624-5bcd-11e8-90a2-a6bc955b3ff5.PNG)

When these errors occur, memory usage goes higher drastically and after they are over, I receive a lot of connection closed messages and then memory usage returns to normal.

**Comment by TGMTProrto** [comment]
Bugs are fixed in the new version(alpha 1.0.4). Use the new version and report it if there is a problem.
