### ISSUE TITLE
Alpha 1.0.3 crash and memory leak

### ISSUE THREAD

**Issue by ffallah** [TGMTProto/MTProtoProxy#12]
After running the app for few hours, the program closes all connections and stops working. although it says all connections are closed, memory usage is still very high which I believe shows a serious memory leak.

![c16](https://user-images.githubusercontent.com/9332653/40283035-6f800d2a-5c8d-11e8-8374-51c7b6301ded.PNG)

**Comment by TGMTProrto** [comment]
I think the problem is from your server side.Bugs are fixed in the new version(alpha 1.0.4). Use the new version and report it if there is a problem.
