### ISSUE TITLE
CRASH - An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by ffallah** [TGMTProto/MTProtoProxy#2]
I had the server running for few hours and suddenly it crashed with the attached error message, when I try to run it again, it crashes within seconds with the same error message.

![c7](https://user-images.githubusercontent.com/9332653/39970441-b8e4f076-5700-11e8-952d-3b5551ded0db.PNG)

Edit: I restarted the server (Windows 2008 R2) and it is not crashing anymore ! I ran it again. will report back if it crashes again.

Edit2: It started to crash again with the same error. restarted the server but it didn't resolve the issue.

**Comment by TGMTProrto** [comment]
This problem appears to be on your server side. Your server may not be able to process large connections. More detailed information is required. Use the new version and report it if there is a problem.

**Comment by ffallah** [comment]
It is definitely not related to number of connections, sometime it crashes within seconds with less than 20 connections. I will report back if new version still crashes.

**Comment by ffallah** [comment]
Well, the new version is not working. but even if the problem was at my side, which is not. This program should not crash with an unhandled exception error. you have to try to catch the exception and deal with it inside the program.

**Comment by NGame1** [comment]
I have the same issue on Windows Server 2008 R2 with only one active connection from my PC.
and I can accept that it sometimes crashes in few seconds when client trying to connect.

**Comment by TGMTProrto** [comment]
@NGame1 I think the problem is from your server side. Use the new version(alpha 1.0.4) and report it if there is a problem.

**Comment by omkarnathsingh** [comment]
This problem is still there on Linux systems.

**Comment by TGMTProrto** [comment]
@omkarnathsingh use it https://t.me/MTProtoProxy/31

**Comment by NGame1** [comment]
Nope in V1.04 alpha issue is still there

**Comment by NGame1** [comment]
OK, this error is still in v1.0.5 alpha. I did this when the proxy fails it will reconnect once again after 1500 milliseconds delay.

```
    class Program
    {
        static MTProtoProxyServer mtprotoProxy;
        static void Main()
        {
            var sec = GenerateRandomSecret();
            var PortNo = 1020;
            mtprotoProxy = new MTProtoProxyServer(sec, PortNo);
            mtprotoProxy.Start();
            string appFileName = Environment.GetCommandLineArgs()[0];
            Console.WriteLine("Proxy server is running. Port:" + PortNo + " Secret:" + sec);
            Console.ReadLine();
            AppDomain.CurrentDomain.UnhandledException += UnhandledExceptionTrapper;
        }

        private static async void UnhandledExceptionTrapper(object sender, UnhandledExceptionEventArgs e)
        {
            await Task.Delay(1500);
            try
            {
                mtprotoProxy.Dispose();
                mtprotoProxy = null;
            }
            catch { }
            finally
            {
                Main();
            }
        }

        public static string GenerateRandomSecret()
        {
            return Guid.NewGuid().ToString().Replace("-", "");
        }
    }
