### ISSUE TITLE
Alpha 1.0.2 reports wrong number of connections

### ISSUE THREAD

**Issue by ffallah** [TGMTProto/MTProtoProxy#9]
![c9](https://user-images.githubusercontent.com/9332653/40132721-c9ea1384-5952-11e8-89b5-f613992ffaa2.PNG)

As you can see in the screenshot, total number of established TCP connections on the server is 341. but MTProtoProxy is reporting more than 3000 connections on the server while only 27 users connected.
I think you are not catching closed connections properly.

Edit : the number of connections is continuously increasing. currently reporting 4000 connections while 360 connections on the server.

**Comment by TGMTProrto** [comment]
This bug has been fixed in the new version(alpha 1.0.3) Use the new version and report it if there is a problem.
